services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db